# Prepares WordPress for use with the local Docker environment.
#
# This action assumes the following:
# - The desired version of NPM has already been installed.author.
# - All Docker environment related variables have been set to the desired values (LOCAL_PHP, LOCAL_PHP_MEMCACHED, etc.).
# - The WordPress/wordpress-develop repository has been checked out.
# - If desired, caching for NPM and Composer dependencies must be pre-configured.
#
# The following steps are performed:
# - Set needed environment variables.
# - Installs NPM dependencies.
# - Installs Composer dependencies.
# - Starts the WordPress Docker container.
# - Starts the memcached server after the Docker network has been created (if desired).
# - Logs the running Docker containers.
# - Install WordPress within the Docker container.
name: Set up WordPress
description: Prepares WordPress for use with the local Docker environment

runs:
  using: "composite"
  steps:
    - name: Configure environment variables
      shell: bash
      run: |
        echo "PHP_FPM_UID=$(id -u)" >> $GITHUB_ENV
        echo "PHP_FPM_GID=$(id -g)" >> $GITHUB_ENV

    - name: Install Dependencies
      shell: bash
      run: npm ci

    - name: Install Composer dependencies
      shell: bash
      run: |
        docker-compose run --rm php composer --version

        # Install using `composer update` as there is no `composer.lock` file.
        if [ ${{ env.LOCAL_PHP }} == '8.1-fpm' ]; then
          docker-compose run --rm php composer update --ignore-platform-reqs
        else
          docker-compose run --rm php composer update
        fi

    - name: Start Docker environment
      shell: bash
      run: npm run env:start

    # The memcached server needs to start after the Docker network has been set up with `npm run env:start`.
    - name: Start the Memcached server.
      shell: bash
      run: |
        if [ ${{ env.LOCAL_PHP_MEMCACHED }} == 'true' ]; then
          cp tests/phpunit/includes/object-cache.php src/wp-content/object-cache.php
          docker run --name memcached --net $(basename "$PWD")_wpdevnet -d memcached
        fi

    - name: Log running Docker containers
      shell: bash
      run: docker ps -a

    - name: Install WordPress
      shell: bash
      run: npm run env:install
